server:
  port: 8080  # Server port

spring:
  # DataSource settings
  datasource:
    url: jdbc:postgresql:moera_naming?characterEncoding=UTF-8
    username: moera
    password: moera
    testWhileIdle: true  # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1

  flyway:
    user: moera
    password: moera
    table: schema_history
    baseline-on-migrate: true

  jpa:
    show-sql: false  # Show or not log for each sql query
    hibernate:
      ddl-auto: none  # Hibernate DDL auto (create, create-drop, update)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # Naming strategy

    # Hibernate native properties (the prefix is
    # stripped before adding them to the entity manager)
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect  # The SQL dialect makes Hibernate generate better SQL for the chosen database

  mustache:
    suffix: .m.html

naming:
  operation-rate: # Operations per minute
    average: 1
    max: 20

  mock-network-latency: false
