server:
  port: 8080  # Server port

spring:
  # DataSource settings
  datasource:
    url: jdbc:postgresql:moera_naming?characterEncoding=UTF-8
    username: moera
    password: moera
    testWhileIdle: true  # Keep the connection alive if idle for a long time (needed in production)
    validationQuery: SELECT 1

  flyway:
    user: moera
    password: moera
    table: schema_history
    baseline-on-migrate: true
    validate-on-migrate: false # To be able to adjust DB schema without validation errors

  jpa:
    show-sql: false  # Show or not log for each sql query
    hibernate:
      ddl-auto: none  # Hibernate DDL auto (create, create-drop, update)
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy  # Naming strategy

  mustache:
    suffix: .m.html

naming:
  generations: []

  operation-rate: # Operations per 10 seconds
    average: 1
    max: 4

  mock-network-latency: false
